### ISSUE TITLE
Safeguard system

### ISSUE THREAD

**Issue by Malabarba** [Fuco1/litable#12]
The readme mentions the possibility of a safeguard system. 

Is that underway? I wouldn't mind lending a hand with that. 

An initial (simple) implementation could check all functions about to be evaluated against a list of "known pure" functions, and quit evaluation if one is not there.

**Comment by Wilfred** [comment]
This is now done, isn't it?

**Comment by Fuco1** [comment]
Yea, Artur added it years ago.  I guess we can close this.
