### ISSUE TITLE
Error when launching M-x litable-mode

### ISSUE THREAD

**Issue by fniessen** [Fuco1/litable#16]
Debugger entered--Lisp error: (invalid-function (value (symbol-value list-symbol)))
  (value (symbol-value list-symbol))()
  litable--dump-list(litable-pure-functions-list)
  litable--save-lists()
  byte-code("\301...)
  autoload-do-load((autoload "litable" "Toggle litable-mode\n\n(fn &optional ARG)" t nil) litable-mode)
  #[1025 "\306...)
  funcall(#[1025 "\306...)
  (with-no-warnings (funcall ad--addoit-function cmd record-flag keys special))
  (setq ad-return-value (with-no-warnings (funcall ad--addoit-function cmd record-flag keys special)))
  (let (ad-return-value) (setq ad-return-value (with-no-warnings (funcall ad--addoit-function cmd record-flag keys special))) (when (fancy-narrow-active-p) (fancy-narrow--motion-function)) ad-return-value)
  ad-Advice-command-execute(#[1025 "\306...)
  apply(ad-Advice-command-execute #[1025 "\306...)
  command-execute(litable-mode record)

Any idea what's going wrong?

Best regards

**Comment by cheunghy** [comment]
Same problem, too

**Comment by m00nlight** [comment]
It worked for me, using Emacs 24.3.1 on linux mint.

**Comment by victorteokw** [comment]
@Fuco1 It takes 10 years for you to close this issue 😊

**Comment by Fuco1** [comment]
I had hundreds of opened issues and got completely overwhelmed to the point I stopped doing anything with github :blush:  I created a project couple days ago and I'm going through everything.  I feel really bad for people who opened pull requests 8 years ago and I missed / ignored them :/

Anyway I tried litable today and it worked for the somewhat simple cases I tried.
