### ISSUE TITLE
Isn't recording new functions; shows "Unsafe function"

### ISSUE THREAD

**Issue by xhevahir** [Fuco1/litable#18]
I seem unable to do much with litable beyond calculating expressions with arithmetic operators. It doesn't seem to be adding any of the functions as I define them, and shows the "Unsafe function" alert whenever I type "defun", or relational operators like < or =, although boolean operators seem to work fine. (I didn't try others.) I'm generally not able to duplicate any of the stuff I've seen in the videos. Any idea what I could be doing wrong?

**Comment by Fuco1** [comment]
You can call `M-x litable-accept-as-pure` to mark found functions as safe.  It will ask for each one if you want to eval it or not.

**Comment by xhevahir** [comment]
Thanks! Don't know why that function wasn't working for me before, but it is now.
