### ISSUE TITLE
Is this project still active? 

### ISSUE THREAD

**Issue by ReneFroger** [Fuco1/litable#19]
I was impressed by your video's. I would like to donate. 

Is there a goal and a roadmap? And I noticed the last activity was more than a year ago. So it makes me to wonder if this project is still active. 

Thanks in advance for your reply.

**Comment by Fuco1** [comment]
It's not active.  This project was mostly just a tech-demo.  I have other active emacs projects which are more useful and so I direct my free time there, you can see them on my profile.

**Comment by ReneFroger** [comment]
Thanks for the reply. It's not so useful indeed, but it's a feature that I wanted so much that I even wanted to donate. Thanks for creating such a project, even it's still not done.

**Comment by Fuco1** [comment]
Hm... seems like you've generated quite a lot of interest :) Hell, maybe I'll get back to it if people find it useful after all (that one calory tracking thing on reddit seems interesting).

**Comment by ReneFroger** [comment]
I can only speak for myself. But I find it very attractive and helpful. No need to C-x C-e anymore to see what's the output is.
