### ISSUE TITLE
Give this project better name

### ISSUE THREAD

**Issue by Fuco1** [Fuco1/litable#2]
Ideas for better name welcome :)

Some objections:
- the idea wasn't invented @ light table, so we shouldn't give credit
- it's too much marketing
- it's too little marketing

**Comment by unhammer** [comment]
> How about victorious.el as a nod to the instigator?

`lysbrett` literally means light-table in Danish/Swedish/Norwegian, and is also a superstring of "bret" :-P

Or how about `victor.el`, which might make people think of both stein's and bret's :-D
