### ISSUE TITLE
Interactively remove function from pure functions list

### ISSUE THREAD

**Issue by MunsterPlop** [Fuco1/litable#22]
Hi,

I'm aware this project isn't really active anymore but it happens I've been using it here and there and I've been missing an interactive way to remove functions from `litable-pure-functions-list` and `litable-list.el`.

Here's a basic proposal using `completing-read` that I've been using:

```elisp
(defun litable-remove-from-pure-list ()
    "Remove a function from the pure functions list."
    (interactive)
    (if (null litable-pure-functions-list)
        (message "No function trusted to be pure.")
      (let ((symbol
             (completing-read "Pure function: "
                              litable-pure-functions-list
                              nil t)))
        (setq litable-pure-functions-list
              (delq (intern symbol) litable-pure-functions-list))
        (litable--save-lists))))
```

Ideally, it could also be made to match the function at point and set it as initial input but I haven't looked into  that.

What do you think?

**Comment by Fuco1** [comment]
hi @MunsterPlop!

If you want, you can turn this into a pull request, I'm happy to merge it.

For the function under point, you can use `symbol-at-point` to grab the name and check with `functionp` if it represents a function (if not, it probably shouldn't be given as a suggestion).

**Comment by MunsterPlop** [comment]
> hi @MunsterPlop!
> 
> If you want, you can turn this into a pull request, I'm happy to merge it.
> 
> For the function under point, you can use `symbol-at-point` to grab the name and check with `functionp` if it represents a function (if not, it probably shouldn't be given as a suggestion).

Thank you for your reply and suggestion,
I made the change and created a pull request.
